VivesTrein/Controllers/BoekingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VivesTrein.Service;
using VivesTrein.Domain;
using VivesTrein.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace VivesTrein.Controllers
{
    [Authorize]
    public class BoekingController : Controller
    {
        private BoekingService boekingService;
        private ReisService reisService;
        private StadService stadService;
        private TreinritService treinritService;
        private TreinritReisService treinritReisService;

        public BoekingController()
        {
            boekingService = new BoekingService();
            reisService = new ReisService();
            stadService = new StadService();
            treinritService = new TreinritService();
            treinritReisService = new TreinritReisService();
        }

        public IActionResult Index()
        {
            string userID = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            IEnumerable<Boeking> listBoeking = boekingService.GetXForUser(userID, 10);

            foreach (var item in listBoeking)
            {
                IEnumerable<TreinritReis> treinritReis = treinritReisService.FindByReisId(item.ReisId);
                Treinrit treinrit = treinritService.FindById(treinritReis.First().TreinritId);
                var vertekDatum = treinrit.Vertrek;

                var dateNow = DateTime.UtcNow;

                if (vertekDatum < dateNow)
                {
                    if (item.Status != "Voltooid")
                    {
                        item.Status = "Voltooid";
                        boekingService.Update(item);
                    }
                }
            }

            foreach (var item in listBoeking)
            {
                IEnumerable<TreinritReis> treinritReis = treinritReisService.FindByReisId(item.ReisId);
                Treinrit treinrit = treinritService.FindById(treinritReis.First().TreinritId);
                var vertekDatum = treinrit.Vertrek;

                var dateNow = DateTime.UtcNow;

                if (vertekDatum < dateNow)
                {
                    if (item.Status != "Voltooid")
                    {
                        item.Status = "Voltooid";
                        boekingService.Update(item);
                    }
                }


                item.Reis = reisService.FindById(item.ReisId);
                item.Reis.Vertrekstad = stadService.FindById(item.Reis.VertrekstadId);
                item.Reis.Bestemmingsstad = stadService.FindById(item.Reis.BestemmingsstadId);
                item.Reis.TreinritReis = treinritReisService.FindByReisId(item.ReisId);

                foreach (var rit in item.Reis.TreinritReis)
                {
                    rit.Treinrit = treinritService.FindById(Convert.ToInt16(rit.TreinritId));
                }
            }

            return View(listBoeking);
        }

        public IActionResult Annuleren (int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // vertrek datum opvragen
            Boeking boeking = boekingService.FindById(id);
            IEnumerable<TreinritReis> treinritReis = treinritReisService.FindByReisId(boeking.ReisId);
            Treinrit treinrit = treinritService.FindById(treinritReis.First().TreinritId);
            var vertekDatum = treinrit.Vertrek;

            var dateNow = DateTime.UtcNow;

            if (boeking.Status != "Geannuleerd")
            {
                if (boeking.Status != "Voltooid")
                {
                    if (dateNow.AddDays(3) < vertekDatum)
                    {
                        boeking.Status = "Geannuleerd";
                        boekingService.Update(boeking);
                    }
                    else
                    {
                        TempData["Message"] = "1";
                    }
                }
                else
                {
                    TempData["Message"] = "2";
                }
            }
            else
            {
                TempData["Message"] = "3"; 
            }

            return RedirectToAction("Index");
        }
    }
}

VivesTrein/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VivesTrein.Extentions;
using VivesTrein.ViewModels;
using VivesTrein.Service;
using VivesTrein.Domain;
using VivesTrein.Domain.Entities;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using VivesTrein.Services;

namespace VivesTrein.Controllers
{
    public class ShoppingCartController : Controller
    {
        private ReisService reisService;
        private BoekingService boekingService;
        private TreinritReisService treinritreisService;
        private StadService stadService;
        private HotelService hotelService;
        private TreinritService treinritService;
        public ShoppingCartController()
        {
            reisService = new ReisService();
            treinritreisService = new TreinritReisService();
            boekingService = new BoekingService();
            stadService = new StadService();
            hotelService = new HotelService();
            treinritService = new TreinritService();
        }


        public IActionResult Index()
        {
            ShoppingCartVM cartList =
                HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart");

            return View(cartList);
        }

        public IActionResult Delete(int? reisId)
        {
            if (reisId == null)
            {
                return NotFound();
            }
            
            ShoppingCartVM cartList = HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart");

            // remove item form shoppingcart
            var itemToRemove = cartList.Cart.FirstOrDefault(r => r.ReisId == reisId);
            if (itemToRemove != null)
            {
                cartList.Cart.Remove(itemToRemove);

                if (cartList.Cart.Count == 0)
                {
                    cartList = null;
                }
                HttpContext.Session.SetObject("ShoppingCart", cartList);

                // remove item from database
                try
                {
                    var toDeleteTreinritreis = treinritreisService.FindByReisId(Convert.ToInt16(reisId));

                    foreach (TreinritReis treinritreis in toDeleteTreinritreis)
                    {
                        //Vrij plaatsen terugzetten
                        Treinrit treinrit = treinritService.FindById(treinritreis.TreinritId);
                        treinrit.Vrijeplaatsen = treinrit.Vrijeplaatsen + 1;
                        treinritService.Update(treinrit);

                        treinritreisService.Delete(treinritreis);
                    }
                    reisService.Delete(reisService.FindById(Convert.ToInt16(reisId)));
                }
                catch (Exception e)
                {
                    Console.Write(e);
                }
            }

            return View("index", cartList);
        }

        public IActionResult DeleteAll()
        {
            ShoppingCartVM cartList = HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart");
            if (cartList != null)
            {
                // remove items from database
                try
                {
                    List<CartVM> carts = cartList.Cart;

                    foreach (CartVM cart in carts)
                    {
                        var toDeleteTreinritreis = treinritreisService.FindByReisId(Convert.ToInt16(cart.ReisId));

                        foreach (TreinritReis treinritreis in toDeleteTreinritreis)
                        {
                            //Vrij plaatsen terugzetten
                            Treinrit treinrit = treinritService.FindById(treinritreis.TreinritId);
                            treinrit.Vrijeplaatsen = treinrit.Vrijeplaatsen + 1;
                            treinritService.Update(treinrit);

                            treinritreisService.Delete(treinritreis);
                        }
                        reisService.Delete(reisService.FindById(Convert.ToInt16(cart.ReisId)));
                    }
                }
                catch (Exception e)
                {
                    Console.Write(e);
                }

                // empty shoppingcart
                cartList = null;
                HttpContext.Session.SetObject("ShoppingCart", cartList);
            }
            
            return View("index", cartList);
        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Payment(ShoppingCartVM model)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }

            List<CartVM> carts = model.Cart;
            List<String> aankomststeden = new List<String>();
            List<Hotel> hotels = new List<Hotel>();

            // opvragen UserId en email
            string userID = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            string userEmail = User.FindFirst(ClaimTypes.Name).Value;

            // opvragen cartlist
            ShoppingCartVM cartList = HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart");
            try
            {
                Boeking boeking;
                var amount = cartList.Cart.Count();
                var begin = "<h2>Hallo " + userEmail + "</h2>" + "<p>U heeft " + amount + " reizen besteld.</p>"; // begin string voor email
                var tickets = "<b>Your tickets:</b>"; // begin voor alle tickets

                foreach (CartVM cart in carts)
                { 
                    // create order object
                    boeking = new Boeking();
                    boeking.UserId = userID;
                    boeking.ReisId = cart.ReisId;
                    boeking.Status = "Betaald";
                    boeking.Datecreated = DateTime.UtcNow;

                    boekingService.Create(boeking);

                    aankomststeden.Add(cart.AankomstStad);

                    // reis in email steken
                    tickets += "<p>Ticket: " + cart.ReisId + " voor " + cart.Naam + " van " + cart.VertrekStad + " naar " + cart.AankomstStad + "</p>";
                }


                // send email
                var body = string.Format(begin + tickets);
                EmailSender mail = new EmailSender();
                await mail.SendEmailAsync(userEmail, "VivesTrein - Ticket(s)", body);


                // zoek hotels voor aankomststad
                foreach(String stadnaam in aankomststeden)
                {
                    IList<Hotel> foundHotels = hotelService.GetHotelsByStadName(stadnaam);
                    foreach(Hotel hotel in foundHotels)
                    {
                        hotels.Add(hotel);
                    }
                }

                // empty shoppingcart
                cartList = null;
                HttpContext.Session.SetObject("ShoppingCart", cartList);
            }
            catch (Exception e)
            {
                Console.Write(e);
            }

            return View(hotels);
        }
    }
}

VivesTrein/Views/ShoppingCart/Index.cshtml
@model VivesTrein.ViewModels.ShoppingCartVM

@{
    ViewData["Title"] = "Index";
}

<h2>Uw winkelmandje:</h2>

@if (Model != null)
{

    <form asp-action="Payment">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Cart[0].Naam)

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cart[0].VertrekStad)

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cart[0].AankomstStad)

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cart[0].Aantal)

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cart[0].Prijs)

                </th>
                <th>
                    Verwijder reis
                </th>
            </tr>
            @{ float total = 0;}
            @for (var i = 0; i < Model.Cart.Count; i++)
            {

                <tr>
                    @Html.HiddenFor(m => Model.Cart[i].ReisId)
                    <td>
                        <input asp-for="@Model.Cart[i].Naam" readonly="readonly" class="form-control" />
                    </td>
                    <td>
                        <input asp-for="@Model.Cart[i].VertrekStad" readonly="readonly" class="form-control" />
                    </td>
                    <td>
                        <input asp-for="@Model.Cart[i].AankomstStad" readonly="readonly" class="form-control" />
                    </td>
                    <td>
                        <input asp-for="@Model.Cart[i].Aantal" type="number" min="1" max="10" data-aantal="@i" readonly="readonly" />
                    </td>
                    <td>
                        <input asp-for="@Model.Cart[i].Prijs" type="number" readonly="readonly" />

                        @{
                            total += Model.Cart[i].Prijs;
                        }

                    </td>
                    <td>
                        <a asp-controller="ShoppingCart" asp-action="Delete" asp-route-reisId="@Model.Cart[i].ReisId">
                            <img src="~/images/redX.png" width="25" height="25" alt="remove this item" />
                        </a>
                    </td>
                </tr>
            }
            <tr>
                <td> <input type="submit" value="Betalen" class="btn btn-default" /></td>
                <td></td>
                <td></td>
                <th>
                    Total:
                </th>
                <td id="cart-total">
                    <input id="txtTotal" value="@total" type="number" readonly="readonly" />
                </td>
            </tr>
            <tr>
                <td></td>
            </tr>
        </table>
    </form>
    <div>
        <a asp-controller="ShoppingCart" asp-action="DeleteAll">
            <img src="~/images/delete.png" width="25" height="25" alt="Empty shoppingcart" /> Winkelmandje leegmaken
        </a>
    </div>
}
else
{
    @Html.Raw("Uw shoppingcart is leeg") <br />
}


<a asp-controller="Reis"
   asp-action="Index">
    Boek een reis
</a> |

<a asp-controller="Home"
   asp-action="Index">
    Ga terug
</a>

VivesTrein/Views/ShoppingCart/Payment.cshtml
@model IEnumerable<VivesTrein.Domain.Entities.Hotel>
@{
    ViewData["Title"] = "Payment";
}

<h2>Betaling bevestigd</h2>
<p>Bedankt om een boeking te plaatsen bij VivesTrein</p><br />
<p>U kan elk moment een mail ontvangen met uw ticket</p><br />
<p>Voor uw historiek klik <a asp-controller="Boeking" asp-action="Index">hier</a></p>
<div class="row">
    <div class="col"><hr></div>
</div>
<h4>Wij hebben enkele hotels voor u gevonden bij aankomst:</h4><br />
<div>
    <table class="table">
        <thead>
            <tr>
                <th class="col-sm-2">
                    Hotelnaam
                </th>
                <th class="col-lg-4">
                    Adres
                </th>
                <th class="col">
                    Link
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="col-sm-2">
                        @Html.DisplayFor(modelItem => item.Naam)
                    </td>
                    <td class="col">
                        @Html.DisplayFor(modelItem => item.Adres)
                    </td>
                    <td class="col">
                        <a>  @Html.DisplayFor(modelItem => item.Link)</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>